Repository googleapis/nodejs-common-grpc, pull requests merged in 2019-05, with the labels that each got.

#229 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#230 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#231 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#235 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: cla: yes

#236 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#237 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#234 build: only pipe to codecov if tests run in Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#238 chore(deps): update @google-cloud/common to v1
  package.json
Labels: cla: yes

#239 chore: remove usage of through
  package.json
  src/service.ts
  test/service.ts
Labels: cla: yes

#240 fix!: upgrade to grpc-js
  package.json
  src/index.ts
  src/service.ts
  test/service.ts
Labels: cla: yes

#241 feat: allow passing grpc in service constructor
  src/service.ts
  test/service.ts
Labels: cla: yes

#242 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#244 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#245 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#248 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#249 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
